Select distinct USERS.NAME,USERS.ADDRESS
FROM USERS
JOIN BOOKINGDETAILS 
ON USERS.USER_ID=BOOKINGDETAILS.USER_ID
WHERE USERS.USER_ID not in(SELECT BOOKINGDETAILS.USER_ID
FROM BOOKINGDETAILS
where BOOKINGDETAILS.NAME IN('HDFC'))
ORDER BY USERS.NAME;

